### PR TITLE
Fix for #6

### PR DESCRIPTION
**Pull request by pobocks**
Adds basic parameter functionality to Saxon::XSLT transform function.

### CODE REVIEW

**Comment by fidothe** [comment]
So, I think the critical thing is to maintain Nokogiri API compatibility - if we're going to support params we should support them exactly as Nokogiri does.

The C code is really hard to read if you're me, but the Java version is thankfully easier to grok: https://github.com/sparklemotion/nokogiri/blob/master/ext/java/nokogiri/XsltStylesheet.java#L106-L135

Basically, it takes both a hash or an array. Should be pretty easy in ruby: if it's a hash, as you were, otherwise if it's an array use something like `array.each_slice(2) { |k, v| ... }` to process the param / value pairs.

**Comment by pobocks** [comment]
Oh, I see. I was going from Noko docs, which only describe Array input AFAICT (http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XSLT/Stylesheet#transform-instance_method)

Will implement as specified.

**Comment by pobocks** [comment]
Hmmm... How closely are we following Noko API.  Saxon XdmAtomicValue has constructor signatures for a variety of value types (various number types, string, qname, etc).  Noko treats all param input as string; thus, in order to pass a string param in Noko, you have to wrap it internally in single quotes:
```ruby
{"this" => "this"}   # produces blank output if param is selected
{"this" => "'this'"} # actually works
```
This seems a little weird to replicate, unless there's some kind of explicit reason behind it, rather than Noko being stringly typed.

**Comment by fidothe** [comment]
It's because with libxml / Xerces you're basically specifying parameters as XPath - if it's a string it has to be quoted, otherwise it's a QName (or maybe a number)

**Comment by pobocks** [comment]
Off the top of my head, tagged string type wrapping QName?

**Comment by pobocks** [comment]
OTOH, I guess if "pass everything as though through `select=`" is expected from Noko/etc, that gives a consistent API with fewer moving parts.  I feel like it should be documented more directly in Noko (and thus here).

I'll see about changing it to resolve to whatever Xdm api represents an XPath expression with.

**Comment by pobocks** [comment]
I spent a bunch of time on a much more complex and terrible solution, and then had an aha moment - why not add an xpath method to the Saxon::XML::Document class?  It'll be useful outside of this context, and it solves the problem in like three lines of code.

This depends on my understanding of xsl:param semantics being correct - that the select attribute is evaluated in context of the XML doc being processed, not the stylesheet.  If I'm wrong, please let me know what the actual semantics are, because the digging through the Saxon docs has destroyed my brain ;-)

**Comment by fidothe** [comment]
I think you're right - I like the approach. I want to take one more pass through the code and then let's get this squashed and merged :-)

**Comment by fidothe** [comment]
I've been trying to figure out how Saxon actually processes parameters, and it looks like they're in `net/sf/saxon/trans/CommandLineOptions.java`. What's in there makes me think that your approach is bang on the money. I should be seeing Michael Kay next month, so I'll make sure I badger him to find out if that approach leaves us open to anything we wouldn't want. If you can squash everything down into one commit, I'll get this merged pronto. I want to add a wrapper for Noko's `XSLT::Stylesheet.apply_to` for the sake of completeness, and then I'll cut the 0.6 release.

**Comment by pobocks** [comment]
Will do!

**Comment by fidothe** [comment]
Thanks!

**Comment by pobocks** [comment]
You're very welcome!

**Pull request merged**
